name: Astrology readings
favicon: null
layout_spectrum: 0.18613
typography_spectrum: 0.57091
title: Astrology Courses and Readings from Michael Conneely
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fdfeff'
    - '#cad5e7'
    - '#4f5048'
    - '#bf998c'
  brandStrength: 0.41095444234088063
  lightness: 0.4583863248117268
  saturation: 0.5967094306834042
  rhythmicContrast: 0.5359840535093099
purpose: []
