name: Astrology readings
favicon: null
layout_spectrum: 0.39712
typography_spectrum: 0.57091
title: Astrology Courses and Readings from Michael Conneely
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fdfeff'
    - '#cad5e7'
    - '#4f5048'
    - '#bf998c'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
