name: Astrology readings
favicon: null
layout_spectrum: 0.1439946077298373
typography_spectrum: 0.57091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.41095444234088063
  lightness: 0.4583863248117268
  saturation: 0.5967094306834042
  rhythmicContrast: 0.5359840535093099
purpose: []
