name: Astrology readings
favicon: null
layout_spectrum: 0.5833
typography_spectrum: 0.57091
title: Astrology Courses and Readings from Michael Conneely
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#1f4456'
    - '#6e6e6e'
    - '#b5b2ad'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
