typography_spectrum: 0.57091
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#1f4456'
    - '#6e6e6e'
    - '#b5b2ad'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5833
analytics:
  google: UA-40654174-2
  facebook: null
  twitter: null
author:
  name: Michael Conneely
  email: michaelconneely@gmail.com
  url: 'http://www.starwheelastrology.com/'
name: Astrology readings
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Learn Vedic Astrology
    id: 62abad9e-5de9-48b3-ab28-0f314c1a58c8
    type: content
favicon: null
title: Astrology Courses and Readings from Michael Conneely
description: The Best In Worldwide Astrology Courses
purpose: []
